server:
  port: 48080

spring:
  application:
    name: yudao-server

  profiles:
    active: local

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。

# todo

--- #################### 芋道相关配置 ####################
yudao:
  info:
    version: 2.0.1
    base-package: com.keer.yudaovue
# todo